spring:
  application:
    name: msa-discovery
server:
  port: 8761
eureka:
  instance:
  client:
    register-With-eureka: true
    fetch-Registry: false
    serviceUrl:
      #
      defaultZone: http://3.226.241.98/:${server.port}/eureka/