spring:
  application:
    name: msa-discovery
server:
  port: 8761
eureka:
  instance:
  client:
    register-With-eureka: true
    fetch-Registry: false
    serviceUrl:
      #
      defaultZone: http://3.213.139.105/:${server.port}/eureka/
