spring:
  application:
    name: msa-discovery
server:
  port: 8761
eureka:
  instance:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
